### ISSUE TITLE
Migrate to Gulp 4.0.

### ISSUE THREAD

**Issue by normmcgarry** [hookerz/gulp-hook-standards-scaffold#3]
I want to get a discussion going about improvements we can make here. I'm not a big fan of the organization of gulp and how the dependencies are just all over the place. I think migrating into gulp 4.0 and use the `parallel` and `series` functions will be more practical for a cleaner and leaner workflow.

**Comment by stevis** [comment]
I'm for a re-work. We had solid intentions but what we have now is pretty clunky and not as configurable as it should be.

**Comment by normmcgarry** [comment]
Merged into master.
